close all;
img = imread('bwimage.png');
H = [1 -2 1];
Y1 = conv2(img,H,"same");
Y2 = conv2(img,H',"same");
figure; imshow(img); title('original');
figure;
subplot(231); imshow(uint8(Y1)); title('Y1 - H');
subplot(232); imshow(uint8(Y2)); title("Y2 - H'");
Y3 = abs(Y1) + abs(Y2);
subplot(233); imshow(uint8(Y3)); title("Y3");
N = normrnd(0,5,size(img));
img = img + uint8(N);
YN1 = conv2(img,H,"same");
YN2 = conv2(img,H',"same");
YN3 = abs(YN1) + abs(YN2);
subplot(236); imshow(uint8(YN3)); title("YN3");
subplot(234); imshow(uint8(YN1)); title('YN1 - H');
subplot(235); imshow(uint8(YN2)); title("YN2 - H'");