close all;
img = imread('kodim08.png');
figure;
cfa = CFA(img);
subplot(231); imshow(uint8(cfa)); title('Mutiplexed Image');
luminance = Luminance(cfa);
subplot(232); imshow(uint8(luminance)); title('Luminance');
mutiplexed_chrominance = MutiplexedChrominance(cfa, luminance);
subplot(234); imshow(uint8(mutiplexed_chrominance)); title('Mutiplexed Chrominance');
subsampled_chrominance = CFA(mutiplexed_chrominance);
subplot(235); imshow(uint8(subsampled_chrominance)); title('Subsampled Chrominance');
chrominance = Interpolation(subsampled_chrominance);
subplot(236); imshow(uint8(chrominance)); title('Chrominance');
rgbimage = RGBImage(luminance,chrominance);
subplot(233); imshow(uint8(rgbimage)); title('RGB Image');
figure;
subplot(121); imshow(uint8(rgbimage)); title('Color Demosaicing');
subplot(122); imshow(uint8(Interpolation(CFA(img)))); title('Bilinear Interpolation');
blimg = uint8(Interpolation(CFA(img)));
rgbimage = uint8(rgbimage);
rgb_ssim = ssim(rgbimage,img);
rgb_psnr = psnr(rgbimage,img);
bln_ssim = ssim(blimg,img);
bln_psnr = psnr(blimg,img);